DELETE FROM Factor1;
DELETE FROM Faktor2;
DELETE FROM InvoiceMap;
DELETE FROM AshkhasList WHERE Code > 1;
DELETE FROM CustomerMap;
DELETE FROM KalaList WHERE Code > 1;
DELETE FROM ProductMap;
DELETE FROM GroupKala;
DELETE FROM CategoryMap;