SELECT * FROM Category;
SELECT * FROM CategoryMap;
SELECT * FROM Product;
SELECT * FROM ProductMap;
SELECT * FROM Customer;
SELECT * FROM CustomerMap;
SELECT * FROM Invoice;
SELECT * FROM InvoiceMap;
SELECT * FROM LineItem;