SELECT * FROM Factor1;
SELECT * FROM Faktor2;
SELECT * FROM InvoiceMap;
SELECT * FROM AshkhasList;
SELECT * FROM CustomerMap;
SELECT * FROM KalaList;
SELECT * FROM ProductMap;
SELECT * FROM GroupKala;
SELECT * FROM CategoryMap;